### ISSUE TITLE
Empty playlists

### ISSUE THREAD

**Issue by erwinkempenaar** [glk1001/glk1001.github.io#13]
Hello,

After installing the spotify v1.3.12 plugin on kodi running on a R-Pi5 and successfully authenticating via the official app it takes a long time to load any playlist and it always returns empty. 

I suppose the following from the kodi.log is relevant:

```
2024-12-25 16:14:54.456 T:4273    error <general>: plugin.audio.spotify:plugin_content:__init__: Exception --> PluginContent init error.
2024-12-25 16:14:54.558 T:4608    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-25 16:14:55.576 T:4608    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 29

2024-12-25 16:15:24.594 T:4608    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-25 16:15:24.595 T:4608    error <general>: ERROR:spotipy.client:Max Retries reached

2024-12-25 16:15:24.601 T:4608    error <general>: plugin.audio.spotify:plugin_content:__init__: urllib3.exceptions.ResponseError: too many 429 error responses

                                                   The above exception was the direct cause of the following exception:

                                                    Traceback (most recent call last):
                                                      File "/home/erwin/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 486, in send
                                                       resp = conn.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/erwin/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 945, in urlopen
                                                       return self.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/erwin/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 945, in urlopen
                                                       return self.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/erwin/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 945, in urlopen
                                                       return self.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/erwin/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 935, in urlopen
                                                       retries = retries.increment(method, url, response=response, _pool=self)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/erwin/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/util.py", line 170, in increment
                                                       return super().increment(method,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/erwin/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 515, in increment
                                                       raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/ (Caused by ResponseError('too many 429 error responses'))
```

Regards,

Erwin Kempenaar

**Comment by linesquarecube** [comment]
Hi,
for me the playlist are not even loading. I get stuck in an infinite loop after selecting `Playlists`, `Albums`, `Songs` or whatever which returns an empty view. Similar log as @erwinkempenaar 
~~~
2024-12-30 23:40:46.703 T:1012     info <general>: plugin.audio.spotify:spotty_helper:__get_linux_spotty_path: Reported architecture: 'aarch64'.
2024-12-30 23:40:46.710 T:1012     info <general>: plugin.audio.spotify:spotty_helper:__test_spotty: ok spotty v1.3.1 - using librespot 0.4.2 d197824 (Built on 2023-08-06, Build ID: wUhGRbBx, Profile: release)
                                                   {"autoplay":true,"debug":false,"lms-auth":true,"ogg-direct":true,"podcasts":true,"save-token":true,"version":"1.3.1","volume-normalisation":true,"zeroconf-port":true}

2024-12-30 23:40:46.712 T:1012     info <general>: plugin.audio.spotify:spotty_helper:__get_spotty_path: Spotty architecture detected. Using spotty binary '/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotty/arm-linux/spotty>
2024-12-30 23:40:46.981 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 7

2024-12-30 23:40:53.737 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:40:55.372 T:1012     info <general>: Skipped 1 duplicate messages..
2024-12-30 23:40:55.372 T:1012     info <general>: plugin.audio.spotify:plugin_content:parse_params: sys.argv = ['plugin://plugin.audio.spotify/', '11', '', 'resume:false']
2024-12-30 23:40:55.373 T:1012     info <general>: plugin.audio.spotify:plugin_content:__init__: Browsing main and setting up precache library.
2024-12-30 23:40:55.404 T:1012     info <general>: plugin.audio.spotify:plugin_content:__browse_main: Finished setting up main menu.
2024-12-30 23:40:55.596 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 29

2024-12-30 23:40:55.756 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:40:58.967 T:1024     info <general>: plugin.audio.spotify:spotty_helper:__get_linux_spotty_path: Reported architecture: 'aarch64'.
2024-12-30 23:40:58.972 T:1024     info <general>: plugin.audio.spotify:spotty_helper:__test_spotty: ok spotty v1.3.1 - using librespot 0.4.2 d197824 (Built on 2023-08-06, Build ID: wUhGRbBx, Profile: release)
                                                   {"autoplay":true,"debug":false,"lms-auth":true,"ogg-direct":true,"podcasts":true,"save-token":true,"version":"1.3.1","volume-normalisation":true,"zeroconf-port":true}

2024-12-30 23:40:58.974 T:1024     info <general>: plugin.audio.spotify:spotty_helper:__get_spotty_path: Spotty architecture detected. Using spotty binary '/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotty/arm-linux/spotty>
2024-12-30 23:40:59.775 T:1024    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 24

2024-12-30 23:41:05.858 T:868      info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 10.
2024-12-30 23:41:23.802 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:41:25.086 T:1024     info <general>: Skipped 1 duplicate messages..
2024-12-30 23:41:25.086 T:1024     info <general>: plugin.audio.spotify:plugin_content:parse_params: sys.argv = ['plugin://plugin.audio.spotify/', '12', '?action=browse_main_library', 'resume:false']
2024-12-30 23:41:25.089 T:1024     info <general>: plugin.audio.spotify:plugin_content:parse_params: Set action to 'browse_main_library'.
2024-12-30 23:41:25.090 T:1024     info <general>: plugin.audio.spotify:plugin_content:__init__: Evaluating action 'browse_main_library'.
2024-12-30 23:41:26.582 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:41:55.728 T:1012     info <general>: Skipped 1 duplicate messages..
2024-12-30 23:41:55.728 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:42:05.863 T:868      info <general>: Skipped 1 duplicate messages..
2024-12-30 23:42:05.863 T:868      info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 20.
2024-12-30 23:42:23.769 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:42:25.680 T:976      info <general>: Skipped 1 duplicate messages..
2024-12-30 23:42:25.680 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:42:39.631 T:1077     info <general>: Skipped 1 duplicate messages..
2024-12-30 23:42:39.631 T:1077     info <general>: plugin.audio.spotify:spotty_helper:__get_linux_spotty_path: Reported architecture: 'aarch64'.
2024-12-30 23:42:39.637 T:1077     info <general>: plugin.audio.spotify:spotty_helper:__test_spotty: ok spotty v1.3.1 - using librespot 0.4.2 d197824 (Built on 2023-08-06, Build ID: wUhGRbBx, Profile: release)
                                                   {"autoplay":true,"debug":false,"lms-auth":true,"ogg-direct":true,"podcasts":true,"save-token":true,"version":"1.3.1","volume-normalisation":true,"zeroconf-port":true}
2024-12-30 23:42:53.727 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:42:55.205 T:1077     info <general>: Skipped 2 duplicate messages..
2024-12-30 23:42:55.205 T:1077     info <general>: plugin.audio.spotify:plugin_content:parse_params: sys.argv = ['plugin://plugin.audio.spotify/', '13', '?action=browse_playlists&ownerid=anit1234-de', 'resume:false']
2024-12-30 23:42:55.207 T:1077     info <general>: plugin.audio.spotify:plugin_content:parse_params: Set action to 'browse_playlists'.
2024-12-30 23:42:55.208 T:1077     info <general>: plugin.audio.spotify:plugin_content:__init__: Evaluating action 'browse_playlists'.
2024-12-30 23:42:55.577 T:1077    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 29

2024-12-30 23:42:55.638 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:43:05.867 T:868      info <general>: Skipped 1 duplicate messages..
2024-12-30 23:43:05.867 T:868      info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 30.
2024-12-30 23:43:23.684 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:43:25.575 T:1077     info <general>: Skipped 1 duplicate messages..
2024-12-30 23:43:25.575 T:1077    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 29

2024-12-30 23:43:25.724 T:976      info <general>: Skipped 1 duplicate messages..
2024-12-30 23:43:25.724 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:43:53.768 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:43:55.658 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:44:05.871 T:868      info <general>: Skipped 2 duplicate messages..
2024-12-30 23:44:05.871 T:868      info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 40.
2024-12-30 23:44:23.702 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1


2024-12-30 23:44:25.591 T:1012     info <general>: Skipped 2 duplicate messages..
2024-12-30 23:44:25.591 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 29

2024-12-30 23:44:25.644 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:44:53.689 T:976      info <general>: Skipped 1 duplicate messages..
2024-12-30 23:44:53.689 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:44:55.699 T:1012     info <general>: Skipped 1 duplicate messages..
2024-12-30 23:44:55.699 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:45:05.874 T:868      info <general>: Skipped 2 duplicate messages..
2024-12-30 23:45:05.874 T:868      info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 50.
2024-12-30 23:45:23.743 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:45:25.581 T:976      info <general>: Skipped 2 duplicate messages..
2024-12-30 23:45:25.581 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 29

2024-12-30 23:45:25.640 T:1077    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:45:53.684 T:1077     info <general>: Skipped 1 duplicate messages..
2024-12-30 23:45:53.684 T:1077    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:45:55.532 T:1077     info <general>: Skipped 1 duplicate messages..
2024-12-30 23:45:55.532 T:1077    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 29

2024-12-30 23:45:55.727 T:1012     info <general>: Skipped 1 duplicate messages..
2024-12-30 23:45:55.727 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:46:05.877 T:868      info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 60.
2024-12-30 23:46:23.775 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:46:25.619 T:1077     info <general>: Skipped 2 duplicate messages..
2024-12-30 23:46:25.619 T:1077    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:46:53.664 T:1077     info <general>: Skipped 2 duplicate messages..
2024-12-30 23:46:53.664 T:1077    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:46:53.665 T:1077    error <general>: ERROR:spotipy.client:Max Retries reached

2024-12-30 23:46:53.682 T:976     error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:46:53.683 T:976     error <general>: ERROR:spotipy.client:Max Retries reached

2024-12-30 23:46:53.699 T:1077    error <general>: plugin.audio.spotify:plugin_content:__init__: urllib3.exceptions.ResponseError: too many 429 error responses
                                                   The above exception was the direct cause of the following exception:

                                                    Traceback (most recent call last):
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 486, in send
                                                       resp = conn.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 945, in urlopen
                                                       return self.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 945, in urlopen
                                                       return self.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 945, in urlopen
                                                       return self.urlopen(

                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 935, in urlopen
                                                       retries = retries.increment(method, url, response=response, _pool=self)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/util.py", line 170, in increment
                                                       return super().increment(method,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 515, in increment
                                                       raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/tracks?limit=50&offset=901&market=DE (Caused by ResponseError(>

                                                   During handling of the above exception, another exception occurred:

                                                    Traceback (most recent call last):
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/client.py", line 270, in _internal_call
                                                       response = self._session.request(
                                                                  ^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 703, in send
                                                       r = adapter.send(request, **kwargs)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 510, in send
                                                       raise RetryError(e, request=request)
                                                    requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/tracks?limit=50&offset=901&market=DE (Caused by ResponseError('t>

                                                   During handling of the above exception, another exception occurred:

                                                    Traceback (most recent call last):
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 88, in __init__
                                                       eval(action)()
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 856, in browse_playlists
                                                       playlists = self.__get_user_playlists(self.__owner_id)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 812, in __get_user_playlists
                                                       checksum = self.__cache_checksum(total)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 219, in __cache_checksum
                                                       saved_tracks = self.__get_saved_track_ids()
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 1514, in __get_saved_track_ids
                                                       saved_tracks["items"] += self.__spotipy.current_user_saved_tracks(
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/client.py", line 1319, in current_user_saved_tracks
                                                       return self._get("me/tracks", limit=limit, offset=offset, market=market)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/client.py", line 327, in _get
                                                       return self._internal_call("GET", url, payload, kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/client.py", line 311, in _internal_call
                                                       raise SpotifyException(
                                                    spotipy.exceptions.SpotifyException: http status: 429, code:-1 - /v1/me/tracks?limit=50&offset=901&market=DE:
                                                    Max Retries, reason: too many 429 error responses

2024-12-30 23:46:53.699 T:1077    error <general>: plugin.audio.spotify:plugin_content:__init__: Exception --> PluginContent init error.
2024-12-30 23:46:53.888 T:976     error <general>: plugin.audio.spotify:plugin_content:__init__: urllib3.exceptions.ResponseError: too many 429 error responses

                                                   The above exception was the direct cause of the following exception:

                                                    Traceback (most recent call last):
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 486, in send
                                                       resp = conn.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 945, in urlopen
                                                       return self.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 945, in urlopen
                                                       return self.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 945, in urlopen
                                                       return self.urlopen(
                                                              ^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 935, in urlopen
                                                       retries = retries.increment(method, url, response=response, _pool=self)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/util.py", line 170, in increment
                                                       return super().increment(method,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 515, in increment
                                                       raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/tracks?limit=50&offset=1951&market=DE (Caused by ResponseError>

                                                   During handling of the above exception, another exception occurred:

                                                    Traceback (most recent call last):
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/client.py", line 270, in _internal_call
                                                       response = self._session.request(
                                                                  ^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 703, in send
                                                       r = adapter.send(request, **kwargs)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 510, in send
                                                       raise RetryError(e, request=request)
                                                    requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/tracks?limit=50&offset=1951&market=DE (Caused by ResponseError('>


                                                   During handling of the above exception, another exception occurred:

                                                    Traceback (most recent call last):
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/client.py", line 270, in _internal_call
                                                       response = self._session.request(
                                                                  ^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 703, in send
                                                       r = adapter.send(request, **kwargs)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 510, in send
                                                       raise RetryError(e, request=request)
                                                    requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/tracks?limit=50&offset=1951&market=DE (Caused by ResponseError('>

                                                   During handling of the above exception, another exception occurred:

                                                    Traceback (most recent call last):
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 88, in __init__
                                                       eval(action)()
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 856, in browse_playlists
                                                       playlists = self.__get_user_playlists(self.__owner_id)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 812, in __get_user_playlists
                                                       checksum = self.__cache_checksum(total)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 219, in __cache_checksum
                                                       saved_tracks = self.__get_saved_track_ids()
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 1514, in __get_saved_track_ids
                                                       saved_tracks["items"] += self.__spotipy.current_user_saved_tracks(
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/client.py", line 1319, in current_user_saved_tracks
                                                       return self._get("me/tracks", limit=limit, offset=offset, market=market)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/client.py", line 327, in _get
                                                       return self._internal_call("GET", url, payload, kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/pi/.kodi/addons/plugin.audio.spotify/resources/lib/deps/spotipy/client.py", line 311, in _internal_call
                                                       raise SpotifyException(
                                                    spotipy.exceptions.SpotifyException: http status: 429, code:-1 - /v1/me/tracks?limit=50&offset=1951&market=DE:
                                                    Max Retries, reason: too many 429 error responses

2024-12-30 23:46:53.888 T:976     error <general>: plugin.audio.spotify:plugin_content:__init__: Exception --> PluginContent init error.
2024-12-30 23:46:54.125 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:46:55.723 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28

2024-12-30 23:47:05.885 T:868      info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 70.
2024-12-30 23:47:23.767 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1

2024-12-30 23:47:25.734 T:1012    error <general>: WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 28


~~~

**Comment by glk1001** [comment]
Hi, Not sure about this. The plugin seems to work fine for Windows and most linux boxes. The rate limit warning is possibly something to do with too many requests. Do you have a playlists with a lot of tracks? Strange that there are two R-Pi5 issues here.

**Comment by erwinkempenaar** [comment]
Hi, 

I installed kodi on Ubuntu 24.04 to test, this installation has the same issues with the same rate/request limit results, I have playlists with a lot of tracks, the strange thing is that it used to work until about 1,5 weeks ago and then it just stopped working. I also tried connecting with my wife's account but this has the same result.

**Comment by erwinkempenaar** [comment]
I fixed the issue, I removed most of my playlists. I also noticed that in nextdns sentry.io was being blocked due to me adding a blocklist. I whitelisted this domain since it is being used for a plethora of api's, now it works again. Not sure if the playlist removals or the sentry.io whitelist fixed it.

Sorry for the inconvenience.

Regards,
Erwin
