### ISSUE TITLE
Spotify addon does not run in LE11.0.1 with Kodi Nexus (20.1)

### ISSUE THREAD

**Issue by jcjdammers** [glk1001/glk1001.github.io#3]
Spotify addon does not run in LE11.0.1 with Kodi Nexus (20.1).
I have installed the addon.
When I run it then it displays a popup window saying it will start the standard browser, when I click OK-button then it hangs.
Do I also first need to install a browser on my LE system?

**Comment by jcjdammers** [comment]
I have installed Chrome web browser, but still the plugin ask for web browser when launched.

**Comment by glk1001** [comment]
Hi, Sorry I haven't been able to try this with LE. The plugin is a python addon and has these python dependencies:

python3-requests python3-urllib3 python3-chardet python3-certifi python3-idna

Not sure if you can get LE to install these

**Comment by glk1001** [comment]
Ignore the above comment. The problem was with a deprecated Python function. I've fixed this and tested on a LibreElec 11 virtual machine. Spotify works fine now.

**Comment by jcjdammers** [comment]
It works now :-), many thanks !!

**Comment by glk1001** [comment]
For LibreElec, tested by two users. Seems OK.

**Comment by jcjdammers** [comment]
Although it works, I a see following error/exception in the kodi.log. Maybe you can have another look? Thanks.

```
2023-04-30 13:38:23.318 T:870     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>=' not supported between instances of 'tuple' and 'int'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 68, in __init__
                                                       self.precache_library()
                                                     File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 1694, in precache_library
                                                       self.get_playlist_details(playlist['owner']['id'], playlist["id"])
                                                     File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 717, in get_playlist_details
                                                       playlistdetails["tracks"]["items"] = self.prepare_track_listitems(
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 976, in prepare_track_listitems
                                                       elif track['album'].get("images"):
                                                            ~~~~~^^^^^^^^^
                                                   KeyError: 'album'

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.spotify/plugin.py", line 14, in <module>
                                                       PluginContent()
                                                     File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 71, in __init__
                                                       log_exception(__name__, exc)
                                                     File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 86, in log_exception
                                                       log_msg(format_exc(sys.exc_info()), xbmc.LOGDEBUG)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/traceback.py", line 187, in format_exc
                                                     File "/usr/lib/python3.11/traceback.py", line 139, in format_exception
                                                     File "/usr/lib/python3.11/traceback.py", line 690, in __init__
                                                     File "/usr/lib/python3.11/traceback.py", line 409, in _extract_from_extended_frame_gen
                                                   TypeError: '>=' not supported between instances of 'tuple' and 'int'
                                                   -->End of Python script error report<--

```

**Comment by glk1001** [comment]
I've added a check for a 'track' not having an 'album'. See if that works.

**Comment by jcjdammers** [comment]
Hi, yes that works, the exception is gone. Thanks.
